# temporary - use only for simple tests
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:oracle:thin:@napsao-qa-nix-melf-oracle-1.qa.vmcommerce.intra:1521/MELF
    username: FEEDS_ADMIN
    password: FEEDS_ADMIN
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    show-sql: true

server:
  port: 8080
  contextPath: /api


#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.show-sql=true
#spring.datasource.url=
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.hikari.connection-timeout=60000
#spring.datasource.hikari.maximum-pool-size=5