server:
  port: 8080
  context-path: /api

spring:
  jackson:
    default-property-inclusion: non_null

  jpa:
    show-sql: true
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: napsao-qa-nix-feeds-elasticsearch-1.qa.vmcommerce.intra:9300
      indexes:
        skus:
          name: skus
          type: sku
  mail:
    host: smtp.qa.vmcommerce.intra:25
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

tagadmin:
    username: admin
    password: admin
    uri: http://vip-cat-serv.qa.vmcommerce.intra/ws/

management:
  security:
    enabled: false

---

spring:
  profiles: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: FEEDS_ADMIN
    password: FEEDS_ADMIN
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

management:
  security:
    enabled: false

---

spring:
  profiles: qa
  datasource:
    url: jdbc:oracle:thin:@napsao-qa-nix-melf-oracle-1.qa.vmcommerce.intra:1521/MELF
    username: FEEDS_ADMIN
    password: FEEDS_ADMIN
    tomcat:
      max-wait: 60000
      initial-size: 10
      max-active: 150
      test-on-borrow: true
  data:
      elasticsearch:
        cluster-name: elasticsearch
        cluster-nodes: napsao-qa-nix-feeds-elasticsearch-1.qa.vmcommerce.intra:9300
        indexes:
          skus:
            name: skus
            type: sku

management:
  security:
    enabled: false
