info:
  component: Feeds Admin Api
  project:
      name: feeds-admin-api
      version: 1.2.8

server:
  port: 8080
  context-path: /admin-api

management:
  security:
    enabled: false

gossip:
  username: ADMIN
  password: 123123
  uri: http://vip-rtg-gossip-serv.qa.vmcommerce.intra:80
  template: FEEDS

spring:
  application:
    name: feeds-admin-api
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: jdbc:oracle:thin:@napsao-qa-nix-melf-oracle-1.qa.vmcommerce.intra:1521/MELF
    username: FEEDS_ADMIN
    password: FEEDS_ADMIN
    tomcat:
      max-wait: 60000
      initial-size: 10
      max-active: 150
      test-on-borrow: true
  data:
    elasticsearch:
      cluster-name: feeds
      cluster-nodes: napsao-qa-nix-feeds-elastic-1.qa.vmcommerce.intra:9300
      indexes:
        skus:
          name: skus
          type: sku

tagadmin:
    username: admin
    password: admin
    uri: http://vip-cat-serv.qa.vmcommerce.intra/ws/

wm:
  swagger:
    keycloak:
      authentication-url: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
      token-url: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
      client:
        id: feeds-admin-api-swagger
        scope:
          name: app-swagger-scope
          description: Global access to endpoints
        credentials:
          secret: 554b3d2b-4a6c-4c57-bc9e-c3de713dc966

keycloak:
  auth-server-url: http://vip-keycloak.qa.vmcommerce.intra/auth
  realm: vmcommerce
  realm-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1omVrjER5CYUmSrp4qB13wQcqy1dD3m7T3LdUUuwRpTM9kqgmixpqSlf0foGqHysEpFKfyx/qta/83SUozyzcE23Y0y9vXJp3jzFHMPSinCBts+tsynIm21Nxbw8CLlJauaHwl5zZcS9xOBN6Z578DfAkHA/OoCS7H2oygaiSuYO2Xz6IFZc4FJbhZVw1RhHjG1UxQy50OjIsb6zK5ALcB6mQQaleKScSOfmVOgN/phudzfpb7bs+1iCFBr9gab/S6+6vT0QH6fqMzW/CQpfFniO4XRESfmCAzJrhtLWjXvUhye1ShO1xMK1BgdoD8O2wtVeJKfD5h58V+LR+vAvbwIDAQAB
  resource: feeds-admin-api
  bearer-only: true
# TODO: Turn on this option when deploy in prod.
#  ssl-required: external
  use-resource-role-mappings: true
  credentials:
    secret: bc3a789e-1e9c-4075-a349-10d43814197a

walmart:
  healthcheck:
    urls:
      elasticsearch: \${spring.data.elasticsearch.cluster-nodes}
      oracle: \${spring.datasource.url}
    probes:
      json:
        gossip-rest:
          url: http://vip-rtg-gossip-serv.qa.vmcommerce.intra:80/rest/healthcheck
          user: ADMIN
          password: 123123
          statusNode: value.appStatus
          statusOK: OK
          kind: EXTERNAL_SERVICE
        tag-admin:
          url: http://vip-cat-serv.qa.vmcommerce.intra:80/ws/status/echo
          user: admin
          password: admin
          statusNode: ok
          statusOK: true
          kind: EXTERNAL_SERVICE