server:
  port: 8080
  context-path: /api

spring:
  jpa:
      show-sql: true

---

spring:
  profiles: local
  datasource:
      url: jdbc:oracle:thin:@localhost:1521/xe
      username: FEEDS_ADMIN
      password: FEEDS_ADMIN
      hikari:
        connection-timeout: 60000
        maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

---

spring:
  profiles: qa
  datasource:
    url: jdbc:oracle:thin:@napsao-qa-nix-melf-oracle-1.qa.vmcommerce.intra:1521/MELF
    username: FEEDS_ADMIN
    password: FEEDS_ADMIN
    tomcat:
      max-wait: 60000
      initial-size: 50
      max-active: 150
      test-on-borrow: true
  jpa:
    show-sql: true